export {default as UserProfile} from './UserProfile';
export {default as TaskCreated} from './TaskCreated';
export {default as TaskPostEdit} from './TaskCreated/TaskPostEdit';
export {default as TaskList} from './TaskList';
export {default as SuccessTask} from './SuccessTask/SuccessTask';
export {default as TaskInner} from './TaskList/TaskInner';
export {default as CalendarTask} from './CalendarTask';
export {default as Company} from './Company';
export {default as CompanyPostEdit} from './Company/CompanyPostEdit';
export {default as CreateWorker} from './Create worker';
export {default as CreateWorkerPostEdit} from './Create worker/CreateWorkerPostEdit';
export {default as Module} from './Module';
export {default as ModulePostEdit} from './Module/ModulePostEdit';
export {default as BossTracking} from './BossTracking';
export {default as ResponsibleUser} from './ResponsibleUser/ResponsibleUser';
export {default as ControllerPanel} from './ControllerPanel';
export {default as Dashboard} from './Dashboard';
export {default as Support} from './Support';
export {default as Inbox} from './Inbox';
export {default as InboxInner} from './Inbox/inboxInner';
export {default as InboxPostEdit} from './Inbox/InboxPostEdit';
export {default as PressCenter} from './press-center/index.jsx';
export {default as NewsInner} from './press-center/newsInner';
export {default as MyApplications} from './MyApplications';
export {default as AddLocationMap} from './Dashboard/map-company/AddLocationMap';
